# Generated by Django 4.2.9 on 2025-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErroSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('view', models.CharField(blank=True, max_length=255)),
                ('usuario', models.CharField(blank=True, max_length=255)),
                ('mensagem', models.TextField()),
                ('stack_trace', models.TextField(blank=True)),
            ],
        ),
    ]
