# Generated by Django 4.2.9 on 2025-06-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errosistema',
            name='acao_corretiva',
            field=models.TextField(blank=True, verbose_name='Ação corretiva'),
        ),
        migrations.AddField(
            model_name='errosistema',
            name='corrigido',
            field=models.BooleanField(default=False, verbose_name='Corrigido?'),
        ),
    ]
